### ISSUE TITLE
ValueObjectBase issue with static final fields

### ISSUE THREAD

**Issue by Derek-Ashmore** [Force66/ValueObjectBase#1]
ValueObjectBase excepts on clone() if the value object defines a static final field.  An example trace follows:

```  
org.force66.beantester.utils.BeanTesterException: Bean implements Clonable, but clone() execution errors
Exception Context:
	[1:class=guru.breakthemonolith.docker.DockerRunSpecification]
---------------------------------
	at org.force66.beantester.tests.ClonableTest.testBeanClass(ClonableTest.java:35)
	at org.force66.beantester.BeanTester.testBean(BeanTester.java:82)
	at org.force66.beantester.BeanTester.testBean(BeanTester.java:69)
	at guru.breakthemonolith.docker.GenericBeanTest.testDockerRunSpecification(GenericBeanTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeMethod(MethodUtils.java:236)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeMethod(MethodUtils.java:270)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeMethod(MethodUtils.java:147)
	at org.force66.beantester.tests.ClonableTest.testBeanClass(ClonableTest.java:33)
	... 26 more
Caused by: org.force66.vobase.ValueObjectException: Problem setting value object field value
Exception Context:
	[1:fieldName=DEFAULT_DETACHED_WAIT_TIME_MILLIS]
	[2:className=guru.breakthemonolith.docker.DockerRunSpecification]
---------------------------------
	at org.force66.vobase.ValueObjectUtils.copyAllFields(ValueObjectUtils.java:42)
	at org.force66.vobase.ValueObjectBase.copy(ValueObjectBase.java:57)
	at org.force66.vobase.ValueObjectBase.clone(ValueObjectBase.java:76)
	... 34 more
Caused by: java.lang.IllegalAccessException: Can not set static final int field guru.breakthemonolith.docker.DockerRunSpecification.DEFAULT_DETACHED_WAIT_TIME_MILLIS to java.lang.Integer
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:73)
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:77)
	at sun.reflect.UnsafeQualifiedStaticIntegerFieldAccessorImpl.set(UnsafeQualifiedStaticIntegerFieldAccessorImpl.java:77)
	at java.lang.reflect.Field.set(Field.java:741)
	at org.apache.commons.lang3.reflect.FieldUtils.writeField(FieldUtils.java:689)
	at org.apache.commons.lang3.reflect.FieldUtils.writeField(FieldUtils.java:789)
	at org.force66.vobase.ValueObjectUtils.copyAllFields(ValueObjectUtils.java:40)
	... 36 more

```

**Comment by Derek-Ashmore** [comment]
This is fixed with rc-2.
